spring:
  application:
    name: Gradleapp
  threads:
    virtual:
      enabled: true
  profiles:
    active: '@spring.profiles.active@'
logging:
  level:
    tech:
      jhipster:
        gradleapp: INFO
server:
  port: 8081
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
        - configprops
        - env
        - health
        - info
        - logfile
        - loggers
        - threaddump
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
